In [1]:
import pandas as pd
import numpy as np
hh="Sample_CSMVW.csv"
hh_df = pd.read_csv(hh)
hh_df.head()

,INSEQNUM,ACTUAL_HHLD_IND,MOSAIC_GROUP_ID,MOSAIC_GROUP_NAME,MOSAIC_SEGMENT_ID,MOSAIC_SEGMENT_NAME,AGE,AGE_MIDPOINT,SIZE1,MARITAL_STATUS,...,PTH_SEGMENT_ID,PTH_SEGMENT_NAME,HCS_SEGMENT_ID,HCS_SEGMENT_NAME,TT_SEGMENT_ID,TT_SEGMENT_NAME,HORMEL_SEGMENT_ID,HORMEL_SEGMENT_NAME,MIL_SEGMENT_ID,MIL_SEGMENT_NAME
0,1817426662,Yes,A,Power Elite,A01,American Royalty,HOH Age 46 - 55,50.5,2 Member HH,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1552308590,Yes,A,Power Elite,A01,American Royalty,HOH Age 26 - 35,30.5,3 Member HH,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2945418244,Yes,A,Power Elite,A01,American Royalty,HOH Age 26 - 35,30.5,1 Member HH,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1794161004,Yes,A,Power Elite,A01,American Royalty,HOH Age 19 - 25,22.0,4 Member HH,Not Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1612042463,Yes,A,Power Elite,A01,American Royalty,HOH Age 26 - 35,30.5,5+ Member HH,Married,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df=pd.DataFrame()
for x in hh_df['AGE'].unique():
       df=df.join((pd.DataFrame(hh_df[hh_df['AGE'] == '{0}'.format(x)].groupby('MOSAIC_SEGMENT_ID')['INSEQNUM'].count()).rename(columns={'INSEQNUM':'{0}'.format(x)})),how='outer')

for x in hh_df['MARITAL_STATUS'].unique():
       df=df.join((pd.DataFrame(hh_df[hh_df['MARITAL_STATUS'] == '{0}'.format(x)].groupby('MOSAIC_SEGMENT_ID')['INSEQNUM'].count()).rename(columns={'INSEQNUM':'{0}'.format(x)})),how='outer')

In [6]:
df

,HOH Age 46 - 55,HOH Age 26 - 35,HOH Age 19 - 25,HOH Age 66+,HOH Age 56 - 65,HOH Age 36 - 45,Married,Not Married
MOSAIC_SEGMENT_ID,,,,,,,,
A01,4.0,5.0,1.0,3.0,5.0,NaN,17.0,1.0
A02,1.0,1.0,1.0,2.0,NaN,NaN,4.0,1.0
A03,4.0,NaN,NaN,NaN,NaN,1.0,5.0,NaN
A04,2.0,NaN,1.0,1.0,NaN,NaN,4.0,NaN
A05,1.0,4.0,NaN,NaN,NaN,6.0,11.0,NaN
A06,1.0,NaN,NaN,3.0,1.0,3.0,2.0,6.0
B07,6.0,2.0,1.0,NaN,3.0,NaN,12.0,NaN
B08,4.0,2.0,NaN,NaN,NaN,6.0,12.0,NaN
B09,1.0,2.0,NaN,NaN,1.0,4.0,8.0,NaN
B10,5.0,3.0,NaN,2.0,2.0,4.0,15.0,1.0
C11,9.0,NaN,NaN,3.0,18.0,NaN,30.0,NaN
C12,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN
C13,2.0,4.0,1.0,19.0,4.0,1.0,28.0,3.0
C14,5.0,NaN,1.0,1.0,4.0,1.0,12.0,NaN
D15,1.0,NaN,1.0,NaN,1.0,9.0,12.0,NaN
D16,2.0,2.0,1.0,2.0,1.0,4.0,10.0,2.0
D17,3.0,NaN,NaN,NaN,NaN,3.0,6.0,NaN
D18,2.0,NaN,1.0,NaN,5.0,2.0,9.0,1.0
E19,1.0,1.0,NaN,2.0,3.0,1.0,7.0,1.0
E20,1.0,6.0,1.0,4.0,7.0,2.0,19.0,2.0
E21,6.0,NaN,NaN,1.0,20.0,NaN,27.0,NaN
F22,NaN,18.0,5.0,NaN,NaN,2.0,24.0,1.0
F23,NaN,2.0,1.0,1.0,NaN,4.0,8.0,NaN
G24,4.0,6.0,1.0,1.0,NaN,6.0,6.0,12.0
G25,1.0,15.0,4.0,NaN,NaN,2.0,1.0,21.0
H26,7.0,NaN,2.0,5.0,2.0,2.0,15.0,3.0
H27,2.0,NaN,NaN,2.0,1.0,3.0,8.0,NaN
H28,1.0,3.0,NaN,1.0,NaN,2.0,7.0,NaN
H29,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN
I30,8.0,5.0,2.0,3.0,2.0,5.0,24.0,1.0
...,...,...,...,...,...,...,...,...
L42,6.0,2.0,NaN,3.0,19.0,2.0,17.0,15.0
L43,9.0,NaN,NaN,2.0,17.0,1.0,23.0,6.0
M44,3.0,5.0,1.0,NaN,NaN,3.0,10.0,2.0
M45,1.0,7.0,2.0,1.0,NaN,4.0,5.0,10.0
N46,2.0,2.0,NaN,3.0,1.0,1.0,7.0,2.0
N47,3.0,5.0,3.0,NaN,1.0,NaN,10.0,2.0
N48,8.0,1.0,NaN,3.0,4.0,1.0,11.0,6.0
N49,1.0,NaN,NaN,NaN,NaN,3.0,3.0,1.0
O50,NaN,NaN,1.0,NaN,NaN,4.0,NaN,5.0
O51,1.0,35.0,6.0,NaN,NaN,1.0,24.0,19.0
O52,5.0,7.0,2.0,1.0,1.0,1.0,3.0,14.0
O53,NaN,2.0,3.0,1.0,1.0,1.0,2.0,6.0
O54,NaN,21.0,3.0,NaN,NaN,NaN,2.0,22.0
O55,NaN,6.0,1.0,1.0,1.0,2.0,5.0,6.0
P56,2.0,NaN,1.0,NaN,NaN,7.0,4.0,6.0
P57,3.0,2.0,NaN,NaN,NaN,2.0,1.0,6.0
P58,2.0,2.0,1.0,NaN,1.0,NaN,1.0,5.0
P59,5.0,NaN,2.0,NaN,2.0,2.0,10.0,1.0
P60,1.0,1.0,NaN,1.0,NaN,4.0,3.0,4.0
P61,2.0,1.0,NaN,NaN,1.0,2.0,2.0,4.0
Q62,NaN,NaN,NaN,9.0,NaN,NaN,4.0,5.0
Q63,NaN,NaN,NaN,1.0,1.0,1.0,3.0,NaN
Q64,NaN,NaN,NaN,41.0,1.0,NaN,26.0,16.0
Q65,NaN,NaN,NaN,15.0,1.0,NaN,3.0,13.0
R66,3.0,6.0,2.0,NaN,NaN,2.0,1.0,12.0
R67,1.0,2.0,2.0,NaN,NaN,2.0,NaN,7.0
S68,3.0,1.0,2.0,2.0,7.0,1.0,5.0,11.0
S69,1.0,NaN,NaN,1.0,6.0,NaN,2.0,6.0
S70,NaN,NaN,1.0,NaN,NaN,1.0,2.0,NaN
S71,1.0,NaN,NaN,1.0,4.0,NaN,NaN,6.0

In [4]:
ninth_df=pd.DataFrame(school_data_complete[school_data_complete['grade'] == "9th"].groupby('school_name')['math_score'].mean()).rename(columns={'math_score':'9th'})
tenth_df=pd.DataFrame(school_data_complete[school_data_complete['grade'] == "10th"].groupby('school_name')['math_score'].mean()).rename(columns={'math_score':'10th'})
elnth_df=pd.DataFrame(school_data_complete[school_data_complete['grade'] == "11th"].groupby('school_name')['math_score'].mean()).rename(columns={'math_score':'11th'})
twlvth_df=pd.DataFrame(school_data_complete[school_data_complete['grade'] == "12th"].groupby('school_name')['math_score'].mean()).rename(columns={'math_score':'12th'})
Math_Scores_By_Grade=pd.concat([ninth_df,tenth_df,elnth_df,twlvth_df],axis=1)
Math_Scores_By_Grade

NameError: name 'school_data_complete' is not defined